# Generated by Django 4.2.4 on 2024-07-10 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adresse',
            name='localite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.localites'),
        ),
    ]
