# Generated by Django 5.0.7 on 2024-07-13 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_userdetail_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='contact',
            field=models.CharField(max_length=15),
        ),
    ]
