# Generated by Django 4.2.4 on 2024-07-15 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_commandes_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commandes',
            name='statut',
            field=models.IntegerField(),
        ),
    ]
