# Generated by Django 4.2.4 on 2024-07-15 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_commandes_statut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='description',
            field=models.CharField(max_length=500),
        ),
    ]
